name: andrewlofthouse
favicon: null
layout_spectrum: 1
typography_spectrum: 0.60695
title: andrew lofthouse photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e0e0e0'
    - '#1c1c1c'
    - '#b20000'
    - '#666666'
    - '#a8a8a8'
  brandStrength: 0.5625
  lightness: 0.9544304416049272
  saturation: 0.0625
  rhythmicContrast: 1
purpose: []
