name: andrewlofthouse
favicon: null
layout_spectrum: 0.91491
typography_spectrum: 0.60695
title: andrew lofthouse photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020202'
    - '#332d31'
    - '#e3e3e3'
    - '#6d666d'
    - '#908687'
  brandStrength: 0.625
  lightness: 0.5
  saturation: 0.0625
  rhythmicContrast: 0.75
purpose: []
