name: andrewlofthouse
favicon: null
layout_spectrum: 0.9081007929053158
typography_spectrum: 0.7068070792593062
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6528657374437898
  lightness: 0.9544304416049272
  saturation: 0.3351827939040959
  rhythmicContrast: 0.9108595766592771
purpose: []
