name: andrewlofthouse
favicon: null
layout_spectrum: 0.91491
typography_spectrum: 0.62102
title: andrew lofthouse photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fdfdfd'
    - '#fe0000'
    - '#6f656d'
    - '#8cc540'
  brandStrength: 0.625
  lightness: 0.125
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
