name: andrew lofthouse
favicon: null
layout_spectrum: 0.50563
typography_spectrum: 0.48589
title: andrew lofthouse photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-72638953-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fe0000'
    - '#ffffff'
    - '#666261'
    - '#979fa1'
  brandStrength: 0
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
