name: andrewlofthouse
favicon: null
layout_spectrum: 0.33544
typography_spectrum: 0.36767
title: andrew lofthouse photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-72638953-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020202'
    - '#b9babc'
    - '#f4f4f4'
    - '#4b4a4f'
    - '#fe3b32'
  brandStrength: 0
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
