typography_spectrum: 0.48589
color:
  brandColors:
    - '#000000'
    - '#fe0000'
    - '#ffffff'
    - '#666261'
    - '#979fa1'
  brandStrength: 0
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.24543
analytics:
  google: UA-72638953-1
  facebook: null
  twitter: null
name: andrew lofthouse
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: andrew lofthouse photography
purpose: []
