name: andrewlofthouse
favicon: null
layout_spectrum: 0.91491
typography_spectrum: 0.61398
title: andrew lofthouse photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#2a2a2a'
    - '#848484'
    - '#b5b5b5'
    - '#e6e6e6'
  brandStrength: 0.625
  lightness: 0.125
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
