name: andrewlofthouse
favicon: null
layout_spectrum: 0.9993
typography_spectrum: 0.54642
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ede9ea'
    - '#34292f'
    - '#bab0af'
    - '#866d70'
  brandStrength: 0.6528657374437898
  lightness: 0.9544304416049272
  saturation: 0.3351827939040959
  rhythmicContrast: 0.9108595766592771
purpose: []
